## Data Preprocessing

In [1]:
# Import the necessary libs
from keras.models import Model
from keras.layers import Input, Dense, Activation
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
sales = pd.read_csv('Data_No_critics.csv')
sales.head()

Platform Manufactur  Year Publisher     NA     EU     JP  Other  Global  \
0      Wii   Nintendo  2006  Nintendo  41.36  28.96   3.77   8.45   82.53   
1      NES   Nintendo  1985  Nintendo  29.08   3.58   6.81   0.77   40.24   
2      Wii   Nintendo  2008  Nintendo  15.68  12.76   3.79   3.29   35.52   
3      Wii   Nintendo  2009  Nintendo  15.61  10.93   3.28   2.95   32.77   
4       GB   Nintendo  1996  Nintendo  11.27   8.89  10.22   1.00   31.37   

  Developer  
0  Nintendo  
1     Other  
2  Nintendo  
3  Nintendo  
4     Other

In [3]:
X = sales.iloc[:, [0,1,2,3,9]]
y_na = sales['NA'].values
y_eu = sales['EU'].values
y_jp = sales['JP'].values
y_other = sales['Other'].values

In [4]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse=False), [0, 1, 2, 3, 4])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X[0,1:].shape

(2334,)

### Splitting the dataset into the Training set and Test set

In [5]:
X_train, X_test, y_na_train, y_na_test, y_eu_train, y_eu_test , y_jp_train, y_jp_test , y_other_train, y_other_test  = train_test_split(X, y_na, y_eu, y_jp, y_other, test_size = 0.2, random_state = 0)

In [6]:
X_train.shape

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
# ??? Is this needed?
 sc = StandardScaler()
 X_train = sc.fit_transform(X_train)
 X_test = sc.transform(X_test)
 X_train

IndentationError: unexpected indent (<ipython-input-7-921a532d91df>, line 2)

## Building the neural network

In [9]:
# Creating the input layer
# 2334 is the number of columns in the X + 1.
my_input = Input(shape=(2335, ))

In [10]:
# Creating first hidden layer
# (input shape + number of outputs) / 2 = (2334 + 4) / 2 = 1169 rounded
# It's necessary to say which layer the hidden layer is connected to. In that case, the input layer
my_hidden_layer_1 = Dense(units=1169, activation='sigmoid')(my_input)

In [11]:
# Creating second hidden layer
my_hidden_layer_2 = Dense(units=1169, activation='sigmoid')(my_hidden_layer_1)

In [12]:
# Create the output layers, one for each continent
# The activation function "linear" keeps the output values
my_output_layer_1 = Dense(units=1, activation='linear')(my_hidden_layer_2)
my_output_layer_2 = Dense(units=1, activation='linear')(my_hidden_layer_2)
my_output_layer_3 = Dense(units=1, activation='linear')(my_hidden_layer_2)
my_output_layer_4 = Dense(units=1, activation='linear')(my_hidden_layer_2)

In [13]:
# Create the model with the inputs and outputs
my_model = Model(inputs=my_input,
                outputs=[my_output_layer_1, my_output_layer_2, my_output_layer_3, my_output_layer_4])

In [14]:
#Compile the model
my_model.compile(optimizer='adam', loss='mse')

In [15]:
# Fit the model WARNING!!! This will take some time.
my_model.fit(X_train, [y_na_train, y_eu_train, y_jp_train, y_other_train],batch_size=100, epochs=1000)

Epoch 1/1000
132/132 [==============================] - 3s 21ms/step - loss: 1.8715 - dense_2_loss: 0.7858 - dense_3_loss: 0.9022 - dense_4_loss: 0.1134 - dense_5_loss: 0.0701
Epoch 2/1000
132/132 [==============================] - 4s 27ms/step - loss: 1.0517 - dense_2_loss: 0.6497 - dense_3_loss: 0.2698 - dense_4_loss: 0.0945 - dense_5_loss: 0.0377
Epoch 3/1000
132/132 [==============================] - 3s 26ms/step - loss: 0.9780 - dense_2_loss: 0.6019 - dense_3_loss: 0.2541 - dense_4_loss: 0.0890 - dense_5_loss: 0.0330
Epoch 4/1000
132/132 [==============================] - 4s 28ms/step - loss: 0.9269 - dense_2_loss: 0.5743 - dense_3_loss: 0.2322 - dense_4_loss: 0.0878 - dense_5_loss: 0.0326
Epoch 5/1000
132/132 [==============================] - 4s 27ms/step - loss: 0.9087 - dense_2_loss: 0.5650 - dense_3_loss: 0.2263 - dense_4_loss: 0.0859 - dense_5_loss: 0.0315
Epoch 6/1000
132/132 [==============================] - 3s 26ms/step - loss: 0.8903 - dense_2_loss: 0.5525 - dense_3_los

132/132 [==============================] - 3s 20ms/step - loss: 0.6454 - dense_2_loss: 0.3929 - dense_3_loss: 0.1632 - dense_4_loss: 0.0650 - dense_5_loss: 0.0243
Epoch 44/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.6538 - dense_2_loss: 0.3994 - dense_3_loss: 0.1661 - dense_4_loss: 0.0635 - dense_5_loss: 0.0248
Epoch 45/1000
132/132 [==============================] - 2s 19ms/step - loss: 0.6782 - dense_2_loss: 0.4193 - dense_3_loss: 0.1704 - dense_4_loss: 0.0643 - dense_5_loss: 0.0242
Epoch 46/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.6441 - dense_2_loss: 0.3966 - dense_3_loss: 0.1592 - dense_4_loss: 0.0639 - dense_5_loss: 0.0244
Epoch 47/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.6099 - dense_2_loss: 0.3698 - dense_3_loss: 0.1550 - dense_4_loss: 0.0622 - dense_5_loss: 0.0230
Epoch 48/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.6130 - dense_2_loss: 0.3731 - dense_3_loss: 0.154

132/132 [==============================] - 3s 20ms/step - loss: 0.5851 - dense_2_loss: 0.3553 - dense_3_loss: 0.1482 - dense_4_loss: 0.0600 - dense_5_loss: 0.0217
Epoch 86/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.5820 - dense_2_loss: 0.3560 - dense_3_loss: 0.1455 - dense_4_loss: 0.0601 - dense_5_loss: 0.0204: 1s - loss: 0.5324 - dense_2_loss: 0.3023 - dense_3_loss: 0.1501 - dense_4_loss: 0.0635 - d
Epoch 87/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.5792 - dense_2_loss: 0.3514 - dense_3_loss: 0.1469 - dense_4_loss: 0.0599 - dense_5_loss: 0.0209
Epoch 88/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.5764 - dense_2_loss: 0.3490 - dense_3_loss: 0.1469 - dense_4_loss: 0.0599 - dense_5_loss: 0.0205
Epoch 89/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.6036 - dense_2_loss: 0.3716 - dense_3_loss: 0.1526 - dense_4_loss: 0.0593 - dense_5_loss: 0.0201
Epoch 90/1000
132/132 [==============

132/132 [==============================] - 3s 20ms/step - loss: 0.5313 - dense_2_loss: 0.3271 - dense_3_loss: 0.1321 - dense_4_loss: 0.0566 - dense_5_loss: 0.0155
Epoch 129/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.5351 - dense_2_loss: 0.3317 - dense_3_loss: 0.1315 - dense_4_loss: 0.0568 - dense_5_loss: 0.0151: 1s - loss: 0.5449 - dense_2_loss: 0.3313 - dense_3_loss: 0.1457 - dense_4_loss: 0.0511 - dense_ - ETA: 0s - loss: 0.5095 - dense_2_loss: 0.3003 - dense_3_loss: 0.1366 - dense_4_loss: 0.0566 - dense_5_loss:
Epoch 130/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.5284 - dense_2_loss: 0.3277 - dense_3_loss: 0.1310 - dense_4_loss: 0.0547 - dense_5_loss: 0.0149
Epoch 131/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.5374 - dense_2_loss: 0.3299 - dense_3_loss: 0.1352 - dense_4_loss: 0.0567 - dense_5_loss: 0.0156
Epoch 132/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.5481 - dense_2_

132/132 [==============================] - 3s 20ms/step - loss: 0.5050 - dense_2_loss: 0.3128 - dense_3_loss: 0.1275 - dense_4_loss: 0.0512 - dense_5_loss: 0.0134: 1s - loss: 0.4593 - dense_2_loss: 0.2788 - dense_3_loss: 0.1156 - dense_4_loss
Epoch 168/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4991 - dense_2_loss: 0.3105 - dense_3_loss: 0.1236 - dense_4_loss: 0.0512 - dense_5_loss: 0.0138
Epoch 169/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.5118 - dense_2_loss: 0.3152 - dense_3_loss: 0.1293 - dense_4_loss: 0.0532 - dense_5_loss: 0.0141
Epoch 170/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.5104 - dense_2_loss: 0.3162 - dense_3_loss: 0.1282 - dense_4_loss: 0.0522 - dense_5_loss: 0.0139
Epoch 171/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.5012 - dense_2_loss: 0.3109 - dense_3_loss: 0.1256 - dense_4_loss: 0.0516 - dense_5_loss: 0.0131
Epoch 172/1000
132/132 [=====================

132/132 [==============================] - 3s 20ms/step - loss: 0.4822 - dense_2_loss: 0.3003 - dense_3_loss: 0.1204 - dense_4_loss: 0.0489 - dense_5_loss: 0.0126
Epoch 209/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.4782 - dense_2_loss: 0.2982 - dense_3_loss: 0.1193 - dense_4_loss: 0.0485 - dense_5_loss: 0.0123: 2s - loss: 0.4193 - dense_2_loss: 0.2095 - dense_3_loss: 0.1269 - dense_4_l
Epoch 210/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4770 - dense_2_loss: 0.2979 - dense_3_loss: 0.1192 - dense_4_loss: 0.0479 - dense_5_loss: 0.0120
Epoch 211/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.4758 - dense_2_loss: 0.2980 - dense_3_loss: 0.1173 - dense_4_loss: 0.0479 - dense_5_loss: 0.0127
Epoch 212/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4733 - dense_2_loss: 0.2948 - dense_3_loss: 0.1185 - dense_4_loss: 0.0472 - dense_5_loss: 0.0128
Epoch 213/1000
132/132 [========================

132/132 [==============================] - 3s 20ms/step - loss: 0.4621 - dense_2_loss: 0.2881 - dense_3_loss: 0.1165 - dense_4_loss: 0.0457 - dense_5_loss: 0.0118: 0s - loss: 0.4927 - dense_2_loss: 0.3143 - dense_3_loss: 0.1233 - dense_4_loss: 0.0421 - dense_5_lo
Epoch 250/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4628 - dense_2_loss: 0.2899 - dense_3_loss: 0.1159 - dense_4_loss: 0.0452 - dense_5_loss: 0.0118: 0s - loss: 0.5021 - dense_2_loss: 0.3198 - dense_3_loss: 0.1254 - dense_4_loss: 0.0450 - dense_5_los
Epoch 251/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.4627 - dense_2_loss: 0.2881 - dense_3_loss: 0.1159 - dense_4_loss: 0.0471 - dense_5_loss: 0.0116
Epoch 252/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4609 - dense_2_loss: 0.2899 - dense_3_loss: 0.1128 - dense_4_loss: 0.0465 - dense_5_loss: 0.0117
Epoch 253/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.4576 - dense_2_loss

132/132 [==============================] - 3s 20ms/step - loss: 0.4545 - dense_2_loss: 0.2862 - dense_3_loss: 0.1112 - dense_4_loss: 0.0451 - dense_5_loss: 0.0119: 2s - loss: 0.3306 - dense_2_loss: 0.1618 - dense_3_loss: 0.0922 - dense_
Epoch 290/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4495 - dense_2_loss: 0.2825 - dense_3_loss: 0.1112 - dense_4_loss: 0.0447 - dense_5_loss: 0.0111
Epoch 291/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4485 - dense_2_loss: 0.2828 - dense_3_loss: 0.1099 - dense_4_loss: 0.0443 - dense_5_loss: 0.0115
Epoch 292/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4570 - dense_2_loss: 0.2881 - dense_3_loss: 0.1115 - dense_4_loss: 0.0460 - dense_5_loss: 0.0115: 0s - loss: 0.3226 - dense_2_loss: 0.1736 - dense_3_loss: 0.0956 - dense_4_loss: 0.0442 - dense_5_l
Epoch 293/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4494 - dense_2_loss: 0.2830 - dense_3_loss: 0.11

132/132 [==============================] - 3s 20ms/step - loss: 0.4335 - dense_2_loss: 0.2731 - dense_3_loss: 0.1066 - dense_4_loss: 0.0430 - dense_5_loss: 0.0108
Epoch 331/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4342 - dense_2_loss: 0.2737 - dense_3_loss: 0.1062 - dense_4_loss: 0.0436 - dense_5_loss: 0.0108
Epoch 332/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4339 - dense_2_loss: 0.2735 - dense_3_loss: 0.1063 - dense_4_loss: 0.0435 - dense_5_loss: 0.0106
Epoch 333/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4315 - dense_2_loss: 0.2728 - dense_3_loss: 0.1052 - dense_4_loss: 0.0427 - dense_5_loss: 0.0108
Epoch 334/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4308 - dense_2_loss: 0.2710 - dense_3_loss: 0.1055 - dense_4_loss: 0.0438 - dense_5_loss: 0.0106
Epoch 335/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4319 - dense_2_loss: 0.2710 - dense_3_loss: 

132/132 [==============================] - 3s 21ms/step - loss: 0.4230 - dense_2_loss: 0.2664 - dense_3_loss: 0.1036 - dense_4_loss: 0.0426 - dense_5_loss: 0.0104
Epoch 374/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.4254 - dense_2_loss: 0.2683 - dense_3_loss: 0.1049 - dense_4_loss: 0.0420 - dense_5_loss: 0.0102
Epoch 375/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.4178 - dense_2_loss: 0.2654 - dense_3_loss: 0.1007 - dense_4_loss: 0.0419 - dense_5_loss: 0.0099
Epoch 376/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4275 - dense_2_loss: 0.2708 - dense_3_loss: 0.1046 - dense_4_loss: 0.0418 - dense_5_loss: 0.0102
Epoch 377/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.4315 - dense_2_loss: 0.2736 - dense_3_loss: 0.1054 - dense_4_loss: 0.0421 - dense_5_loss: 0.0105
Epoch 378/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4242 - dense_2_loss: 0.2685 - dense_3_loss: 

132/132 [==============================] - 3s 20ms/step - loss: 0.4168 - dense_2_loss: 0.2638 - dense_3_loss: 0.1013 - dense_4_loss: 0.0415 - dense_5_loss: 0.0103
Epoch 413/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4169 - dense_2_loss: 0.2651 - dense_3_loss: 0.0993 - dense_4_loss: 0.0425 - dense_5_loss: 0.0100
Epoch 414/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4119 - dense_2_loss: 0.2623 - dense_3_loss: 0.0991 - dense_4_loss: 0.0409 - dense_5_loss: 0.0096
Epoch 415/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.4104 - dense_2_loss: 0.2607 - dense_3_loss: 0.0986 - dense_4_loss: 0.0412 - dense_5_loss: 0.0098
Epoch 416/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4172 - dense_2_loss: 0.2637 - dense_3_loss: 0.1016 - dense_4_loss: 0.0422 - dense_5_loss: 0.0097: 0s - loss: 0.4348 - dense_2_loss: 0.2748 - dense_3_loss: 0.1070 - dense_4_loss: 0.0427 - dense_5_loss: 0
Epoch 417/1000
132/

132/132 [==============================] - 3s 20ms/step - loss: 0.4150 - dense_2_loss: 0.2648 - dense_3_loss: 0.0997 - dense_4_loss: 0.0403 - dense_5_loss: 0.0102
Epoch 454/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4091 - dense_2_loss: 0.2607 - dense_3_loss: 0.0983 - dense_4_loss: 0.0402 - dense_5_loss: 0.0097
Epoch 455/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.4097 - dense_2_loss: 0.2610 - dense_3_loss: 0.0975 - dense_4_loss: 0.0414 - dense_5_loss: 0.0098
Epoch 456/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4128 - dense_2_loss: 0.2620 - dense_3_loss: 0.1009 - dense_4_loss: 0.0404 - dense_5_loss: 0.0095
Epoch 457/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.4096 - dense_2_loss: 0.2605 - dense_3_loss: 0.0986 - dense_4_loss: 0.0409 - dense_5_loss: 0.0096
Epoch 458/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.4030 - dense_2_loss: 0.2563 - dense_3_loss: 

132/132 [==============================] - 3s 23ms/step - loss: 0.4004 - dense_2_loss: 0.2551 - dense_3_loss: 0.0959 - dense_4_loss: 0.0401 - dense_5_loss: 0.0092
Epoch 497/1000
132/132 [==============================] - 3s 23ms/step - loss: 0.4038 - dense_2_loss: 0.2587 - dense_3_loss: 0.0966 - dense_4_loss: 0.0392 - dense_5_loss: 0.0093
Epoch 498/1000
132/132 [==============================] - 3s 22ms/step - loss: 0.4048 - dense_2_loss: 0.2581 - dense_3_loss: 0.0974 - dense_4_loss: 0.0397 - dense_5_loss: 0.0097
Epoch 499/1000
132/132 [==============================] - 3s 23ms/step - loss: 0.4013 - dense_2_loss: 0.2564 - dense_3_loss: 0.0957 - dense_4_loss: 0.0396 - dense_5_loss: 0.0096
Epoch 500/1000
132/132 [==============================] - 3s 24ms/step - loss: 0.3989 - dense_2_loss: 0.2549 - dense_3_loss: 0.0949 - dense_4_loss: 0.0400 - dense_5_loss: 0.0091
Epoch 501/1000
132/132 [==============================] - 3s 24ms/step - loss: 0.4029 - dense_2_loss: 0.2570 - dense_3_loss: 

132/132 [==============================] - 3s 23ms/step - loss: 0.3980 - dense_2_loss: 0.2543 - dense_3_loss: 0.0943 - dense_4_loss: 0.0394 - dense_5_loss: 0.0100
Epoch 542/1000
132/132 [==============================] - 3s 25ms/step - loss: 0.4010 - dense_2_loss: 0.2588 - dense_3_loss: 0.0942 - dense_4_loss: 0.0388 - dense_5_loss: 0.0093: 2s - loss: 0.9107 - dense_2_loss: 0.6502 - dense_3_loss: 0.1922 - dense_4_loss: 0.0517 - dense_5_lo - ETA: 2s - loss: 0.6682 - dense_2_loss: 0.4518 - dense_3_loss: 0.1593 - dense_
Epoch 543/1000
132/132 [==============================] - 3s 25ms/step - loss: 0.3999 - dense_2_loss: 0.2558 - dense_3_loss: 0.0941 - dense_4_loss: 0.0408 - dense_5_loss: 0.0093
Epoch 544/1000
132/132 [==============================] - 3s 24ms/step - loss: 0.4008 - dense_2_loss: 0.2563 - dense_3_loss: 0.0957 - dense_4_loss: 0.0391 - dense_5_loss: 0.0097
Epoch 545/1000
132/132 [==============================] - 3s 24ms/step - loss: 0.4018 - dense_2_loss: 0.2545 - dense_3_los

132/132 [==============================] - 3s 23ms/step - loss: 0.3988 - dense_2_loss: 0.2555 - dense_3_loss: 0.0946 - dense_4_loss: 0.0392 - dense_5_loss: 0.0094
Epoch 584/1000
132/132 [==============================] - 3s 23ms/step - loss: 0.3983 - dense_2_loss: 0.2554 - dense_3_loss: 0.0944 - dense_4_loss: 0.0393 - dense_5_loss: 0.0092
Epoch 585/1000
132/132 [==============================] - 3s 24ms/step - loss: 0.3947 - dense_2_loss: 0.2522 - dense_3_loss: 0.0938 - dense_4_loss: 0.0391 - dense_5_loss: 0.0096
Epoch 586/1000
132/132 [==============================] - 3s 24ms/step - loss: 0.4010 - dense_2_loss: 0.2573 - dense_3_loss: 0.0947 - dense_4_loss: 0.0400 - dense_5_loss: 0.0091
Epoch 587/1000
132/132 [==============================] - 3s 22ms/step - loss: 0.3979 - dense_2_loss: 0.2548 - dense_3_loss: 0.0939 - dense_4_loss: 0.0399 - dense_5_loss: 0.0093
Epoch 588/1000
132/132 [==============================] - 3s 22ms/step - loss: 0.3994 - dense_2_loss: 0.2563 - dense_3_loss: 

132/132 [==============================] - 3s 22ms/step - loss: 0.3939 - dense_2_loss: 0.2525 - dense_3_loss: 0.0934 - dense_4_loss: 0.0390 - dense_5_loss: 0.0090
Epoch 628/1000
132/132 [==============================] - 3s 22ms/step - loss: 0.3938 - dense_2_loss: 0.2528 - dense_3_loss: 0.0937 - dense_4_loss: 0.0382 - dense_5_loss: 0.0090
Epoch 629/1000
132/132 [==============================] - 3s 22ms/step - loss: 0.3993 - dense_2_loss: 0.2565 - dense_3_loss: 0.0947 - dense_4_loss: 0.0391 - dense_5_loss: 0.0090
Epoch 630/1000
132/132 [==============================] - 3s 23ms/step - loss: 0.3979 - dense_2_loss: 0.2543 - dense_3_loss: 0.0939 - dense_4_loss: 0.0402 - dense_5_loss: 0.0095
Epoch 631/1000
132/132 [==============================] - 3s 22ms/step - loss: 0.3948 - dense_2_loss: 0.2521 - dense_3_loss: 0.0936 - dense_4_loss: 0.0394 - dense_5_loss: 0.0097
Epoch 632/1000
132/132 [==============================] - 3s 23ms/step - loss: 0.3917 - dense_2_loss: 0.2510 - dense_3_loss: 

132/132 [==============================] - 3s 23ms/step - loss: 0.3926 - dense_2_loss: 0.2532 - dense_3_loss: 0.0925 - dense_4_loss: 0.0382 - dense_5_loss: 0.0088
Epoch 673/1000
132/132 [==============================] - 3s 22ms/step - loss: 0.3924 - dense_2_loss: 0.2512 - dense_3_loss: 0.0943 - dense_4_loss: 0.0383 - dense_5_loss: 0.0086
Epoch 674/1000
132/132 [==============================] - 3s 23ms/step - loss: 0.3930 - dense_2_loss: 0.2529 - dense_3_loss: 0.0933 - dense_4_loss: 0.0379 - dense_5_loss: 0.0090
Epoch 675/1000
132/132 [==============================] - 3s 23ms/step - loss: 0.3907 - dense_2_loss: 0.2510 - dense_3_loss: 0.0923 - dense_4_loss: 0.0383 - dense_5_loss: 0.0091
Epoch 676/1000
132/132 [==============================] - 3s 23ms/step - loss: 0.3940 - dense_2_loss: 0.2523 - dense_3_loss: 0.0938 - dense_4_loss: 0.0384 - dense_5_loss: 0.0094
Epoch 677/1000
132/132 [==============================] - 3s 23ms/step - loss: 0.3957 - dense_2_loss: 0.2525 - dense_3_loss: 

132/132 [==============================] - 3s 22ms/step - loss: 0.3941 - dense_2_loss: 0.2530 - dense_3_loss: 0.0932 - dense_4_loss: 0.0393 - dense_5_loss: 0.0086
Epoch 717/1000
132/132 [==============================] - 3s 22ms/step - loss: 0.3935 - dense_2_loss: 0.2525 - dense_3_loss: 0.0929 - dense_4_loss: 0.0392 - dense_5_loss: 0.0089: 1s - loss: 0.3631 - dense_2_loss: 0.2385 - dense_3_loss: 0.0799 - dense_4_loss: 0.0361 - de
Epoch 718/1000
132/132 [==============================] - 3s 22ms/step - loss: 0.3934 - dense_2_loss: 0.2530 - dense_3_loss: 0.0930 - dense_4_loss: 0.0383 - dense_5_loss: 0.0091
Epoch 719/1000
132/132 [==============================] - 4s 29ms/step - loss: 0.3911 - dense_2_loss: 0.2505 - dense_3_loss: 0.0927 - dense_4_loss: 0.0390 - dense_5_loss: 0.0089: 3s - loss: 0.4406 - dense_2_loss: 0.2640 - dense_3_loss: 0.1
Epoch 720/1000
132/132 [==============================] - 3s 24ms/step - loss: 0.3916 - dense_2_loss: 0.2508 - dense_3_loss: 0.0924 - dense_4_loss: 

132/132 [==============================] - 3s 20ms/step - loss: 0.3920 - dense_2_loss: 0.2521 - dense_3_loss: 0.0923 - dense_4_loss: 0.0386 - dense_5_loss: 0.0090
Epoch 759/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.3913 - dense_2_loss: 0.2509 - dense_3_loss: 0.0911 - dense_4_loss: 0.0399 - dense_5_loss: 0.0094
Epoch 760/1000
132/132 [==============================] - 3s 24ms/step - loss: 0.3917 - dense_2_loss: 0.2508 - dense_3_loss: 0.0917 - dense_4_loss: 0.0401 - dense_5_loss: 0.0092
Epoch 761/1000
132/132 [==============================] - 3s 19ms/step - loss: 0.3923 - dense_2_loss: 0.2527 - dense_3_loss: 0.0924 - dense_4_loss: 0.0386 - dense_5_loss: 0.0087
Epoch 762/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.3869 - dense_2_loss: 0.2496 - dense_3_loss: 0.0912 - dense_4_loss: 0.0376 - dense_5_loss: 0.0085
Epoch 763/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.3910 - dense_2_loss: 0.2502 - dense_3_loss: 

132/132 [==============================] - 3s 21ms/step - loss: 0.3908 - dense_2_loss: 0.2511 - dense_3_loss: 0.0921 - dense_4_loss: 0.0386 - dense_5_loss: 0.0090
Epoch 799/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.3935 - dense_2_loss: 0.2537 - dense_3_loss: 0.0924 - dense_4_loss: 0.0389 - dense_5_loss: 0.0085
Epoch 800/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.3891 - dense_2_loss: 0.2502 - dense_3_loss: 0.0931 - dense_4_loss: 0.0371 - dense_5_loss: 0.0088
Epoch 801/1000
132/132 [==============================] - 3s 24ms/step - loss: 0.3886 - dense_2_loss: 0.2499 - dense_3_loss: 0.0922 - dense_4_loss: 0.0380 - dense_5_loss: 0.0085
Epoch 802/1000
132/132 [==============================] - 3s 25ms/step - loss: 0.3891 - dense_2_loss: 0.2515 - dense_3_loss: 0.0905 - dense_4_loss: 0.0384 - dense_5_loss: 0.0087
Epoch 803/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.3902 - dense_2_loss: 0.2507 - dense_3_loss: 

132/132 [==============================] - 3s 21ms/step - loss: 0.3906 - dense_2_loss: 0.2502 - dense_3_loss: 0.0935 - dense_4_loss: 0.0384 - dense_5_loss: 0.0084
Epoch 839/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.3910 - dense_2_loss: 0.2534 - dense_3_loss: 0.0914 - dense_4_loss: 0.0376 - dense_5_loss: 0.0086
Epoch 840/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.3914 - dense_2_loss: 0.2529 - dense_3_loss: 0.0918 - dense_4_loss: 0.0382 - dense_5_loss: 0.0085
Epoch 841/1000
132/132 [==============================] - 3s 22ms/step - loss: 0.3876 - dense_2_loss: 0.2496 - dense_3_loss: 0.0917 - dense_4_loss: 0.0375 - dense_5_loss: 0.0088: 2s - loss: 0.6489 - dense_2_loss: 0.4011 - dense_3_loss: 0.1699 - dense_4_loss: 0.0616 - dense_5_loss:  - ETA: 1s - loss: 0.4653 - dense_2_loss: 0.3207 - dense_3_loss: 0.0935 - dense_
Epoch 842/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.3898 - dense_2_loss: 0.2507 - dense_3

132/132 [==============================] - 3s 21ms/step - loss: 0.3883 - dense_2_loss: 0.2494 - dense_3_loss: 0.0925 - dense_4_loss: 0.0378 - dense_5_loss: 0.0086
Epoch 881/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.3870 - dense_2_loss: 0.2497 - dense_3_loss: 0.0911 - dense_4_loss: 0.0376 - dense_5_loss: 0.0086
Epoch 882/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.3952 - dense_2_loss: 0.2558 - dense_3_loss: 0.0933 - dense_4_loss: 0.0375 - dense_5_loss: 0.0086
Epoch 883/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.3861 - dense_2_loss: 0.2485 - dense_3_loss: 0.0912 - dense_4_loss: 0.0380 - dense_5_loss: 0.0084
Epoch 884/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.3878 - dense_2_loss: 0.2497 - dense_3_loss: 0.0916 - dense_4_loss: 0.0381 - dense_5_loss: 0.0085: 1s - loss: 0.4853 - dense_2_loss: 0.3760 - dense_3_loss: 0.0504 - dense_4_l
Epoch 885/1000
132/132 [========================

132/132 [==============================] - 3s 20ms/step - loss: 0.3891 - dense_2_loss: 0.2514 - dense_3_loss: 0.0903 - dense_4_loss: 0.0385 - dense_5_loss: 0.0089
Epoch 920/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.3920 - dense_2_loss: 0.2536 - dense_3_loss: 0.0920 - dense_4_loss: 0.0376 - dense_5_loss: 0.0089
Epoch 921/1000
132/132 [==============================] - 3s 22ms/step - loss: 0.3875 - dense_2_loss: 0.2499 - dense_3_loss: 0.0902 - dense_4_loss: 0.0386 - dense_5_loss: 0.0087
Epoch 922/1000
132/132 [==============================] - 3s 23ms/step - loss: 0.3900 - dense_2_loss: 0.2515 - dense_3_loss: 0.0921 - dense_4_loss: 0.0378 - dense_5_loss: 0.0086: 2s - loss: 0.1841 - dense_2_loss: 0.0881 - dense_3_loss: 0.051
Epoch 923/1000
132/132 [==============================] - 3s 23ms/step - loss: 0.3883 - dense_2_loss: 0.2491 - dense_3_loss: 0.0930 - dense_4_loss: 0.0375 - dense_5_loss: 0.0087: 0s - loss: 0.4216 - dense_2_loss: 0.2802 - dense_3_loss: 0.0

132/132 [==============================] - 3s 20ms/step - loss: 0.3840 - dense_2_loss: 0.2478 - dense_3_loss: 0.0902 - dense_4_loss: 0.0376 - dense_5_loss: 0.0084
Epoch 961/1000
132/132 [==============================] - 3s 20ms/step - loss: 0.3908 - dense_2_loss: 0.2520 - dense_3_loss: 0.0933 - dense_4_loss: 0.0370 - dense_5_loss: 0.0085
Epoch 962/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.3902 - dense_2_loss: 0.2529 - dense_3_loss: 0.0908 - dense_4_loss: 0.0376 - dense_5_loss: 0.0089
Epoch 963/1000
132/132 [==============================] - 3s 21ms/step - loss: 0.3862 - dense_2_loss: 0.2491 - dense_3_loss: 0.0910 - dense_4_loss: 0.0374 - dense_5_loss: 0.0088
Epoch 964/1000
132/132 [==============================] - 3s 25ms/step - loss: 0.3870 - dense_2_loss: 0.2503 - dense_3_loss: 0.0906 - dense_4_loss: 0.0376 - dense_5_loss: 0.0085: 0s - loss: 0.4354 - dense_2_loss: 0.2953 - dense_3_loss: 0.0959 - dense_4_loss: 0.0353 - den
Epoch 965/1000
132/132 [=======

In [16]:
# Save the model
my_model.save('./checkpoints/my_model')
my_model.history

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: ./checkpoints/my_model\assets


### Predicting the results of the Test set

In [17]:
y_pred = my_model.predict(X_test)
y_pred

[array([[0.06203026],
        [0.46980804],
        [0.16945285],
        ...,
        [0.15319985],
        [0.03833431],
        [0.08236617]], dtype=float32),
 array([[0.02217173],
        [0.17538255],
        [0.10032842],
        ...,
        [0.4415771 ],
        [0.01971347],
        [0.01547911]], dtype=float32),
 array([[0.04466831],
        [0.05294503],
        [0.05312029],
        ...,
        [0.05506755],
        [0.12895405],
        [0.11623155]], dtype=float32),
 array([[-0.00813916],
        [ 0.01820244],
        [ 0.02305236],
        ...,
        [ 0.20677377],
        [-0.01314576],
        [-0.00308765]], dtype=float32)]

In [18]:
np.set_printoptions(precision=2)

In [19]:
y_pred = y_pred[0]
y_pred

array([[0.06],
       [0.47],
       [0.17],
       ...,
       [0.15],
       [0.04],
       [0.08]], dtype=float32)

In [20]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_na_test.reshape(len(y_na_test),1)),1))

[[0.06 0.04]
 [0.47 0.3 ]
 [0.17 0.36]
 ...
 [0.15 0.33]
 [0.04 0.  ]
 [0.08 0.05]]


### Evaluate the test data

In [21]:
print("Evaluate on test data")
results = my_model.evaluate(X_test, [y_na_test, y_eu_test , y_jp_test , y_other_test], batch_size=128)
print("test loss, test acc:", results)

Evaluate on test data
26/26 [==============================] - 0s 5ms/step - loss: 0.9515 - dense_2_loss: 0.6592 - dense_3_loss: 0.1878 - dense_4_loss: 0.0711 - dense_5_loss: 0.0334
test loss, test acc: [0.9515253901481628, 0.6591928601264954, 0.18780256807804108, 0.07110823690891266, 0.033421698957681656]


In [24]:
print("Accuracy North America: %.2f%%" % (results[1]*100))
print("Accuracy Europe: %.2f%%" % (results[2]*100))
print("Accuracy Japan: %.2f%%" % (results[3]*100))
print("Accuracy Other: %.2f%%" % (results[4]*100))
print("Total test Loss: %.2f%%" % (results[0]*100))

Accuracy North America: 65.92%
Accuracy Europe: 18.78%
Accuracy Japan: 7.11%
Accuracy Other: 3.34%
Total test Loss: 95.15%
